// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connection.proto

package connection_grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthResponse_ResultMessage int32

const (
	AuthResponse_MESSAGE_FAILED  AuthResponse_ResultMessage = 0
	AuthResponse_MESSAGE_SUCCESS AuthResponse_ResultMessage = 1
)

var AuthResponse_ResultMessage_name = map[int32]string{
	0: "MESSAGE_FAILED",
	1: "MESSAGE_SUCCESS",
}

var AuthResponse_ResultMessage_value = map[string]int32{
	"MESSAGE_FAILED":  0,
	"MESSAGE_SUCCESS": 1,
}

func (x AuthResponse_ResultMessage) String() string {
	return proto.EnumName(AuthResponse_ResultMessage_name, int32(x))
}

func (AuthResponse_ResultMessage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{4, 0}
}

type RequestUserIdResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestUserIdResponse) Reset()         { *m = RequestUserIdResponse{} }
func (m *RequestUserIdResponse) String() string { return proto.CompactTextString(m) }
func (*RequestUserIdResponse) ProtoMessage()    {}
func (*RequestUserIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{0}
}

func (m *RequestUserIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestUserIdResponse.Unmarshal(m, b)
}
func (m *RequestUserIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestUserIdResponse.Marshal(b, m, deterministic)
}
func (m *RequestUserIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestUserIdResponse.Merge(m, src)
}
func (m *RequestUserIdResponse) XXX_Size() int {
	return xxx_messageInfo_RequestUserIdResponse.Size(m)
}
func (m *RequestUserIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestUserIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestUserIdResponse proto.InternalMessageInfo

func (m *RequestUserIdResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ConnectionRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionRequest) Reset()         { *m = ConnectionRequest{} }
func (m *ConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectionRequest) ProtoMessage()    {}
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{1}
}

func (m *ConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionRequest.Unmarshal(m, b)
}
func (m *ConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionRequest.Marshal(b, m, deterministic)
}
func (m *ConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionRequest.Merge(m, src)
}
func (m *ConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectionRequest.Size(m)
}
func (m *ConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionRequest proto.InternalMessageInfo

func (m *ConnectionRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ConnectionResponse struct {
	ConnectionCode       string   `protobuf:"bytes,1,opt,name=connectionCode,proto3" json:"connectionCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionResponse) Reset()         { *m = ConnectionResponse{} }
func (m *ConnectionResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectionResponse) ProtoMessage()    {}
func (*ConnectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{2}
}

func (m *ConnectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionResponse.Unmarshal(m, b)
}
func (m *ConnectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionResponse.Marshal(b, m, deterministic)
}
func (m *ConnectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionResponse.Merge(m, src)
}
func (m *ConnectionResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectionResponse.Size(m)
}
func (m *ConnectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionResponse proto.InternalMessageInfo

func (m *ConnectionResponse) GetConnectionCode() string {
	if m != nil {
		return m.ConnectionCode
	}
	return ""
}

type AuthRequest struct {
	ConnectionCode       string   `protobuf:"bytes,1,opt,name=connectionCode,proto3" json:"connectionCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{3}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetConnectionCode() string {
	if m != nil {
		return m.ConnectionCode
	}
	return ""
}

type AuthResponse struct {
	Message              AuthResponse_ResultMessage `protobuf:"varint,1,opt,name=message,proto3,enum=connection_grpc.AuthResponse_ResultMessage" json:"message,omitempty"`
	UserId               string                     `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{4}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetMessage() AuthResponse_ResultMessage {
	if m != nil {
		return m.Message
	}
	return AuthResponse_MESSAGE_FAILED
}

func (m *AuthResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterEnum("connection_grpc.AuthResponse_ResultMessage", AuthResponse_ResultMessage_name, AuthResponse_ResultMessage_value)
	proto.RegisterType((*RequestUserIdResponse)(nil), "connection_grpc.RequestUserIdResponse")
	proto.RegisterType((*ConnectionRequest)(nil), "connection_grpc.ConnectionRequest")
	proto.RegisterType((*ConnectionResponse)(nil), "connection_grpc.ConnectionResponse")
	proto.RegisterType((*AuthRequest)(nil), "connection_grpc.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "connection_grpc.AuthResponse")
}

func init() { proto.RegisterFile("connection.proto", fileDescriptor_51baa40a1cc6b48b) }

var fileDescriptor_51baa40a1cc6b48b = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0xed, 0x90, 0x89, 0x57, 0xdd, 0x66, 0xc4, 0x21, 0x53, 0x41, 0x2a, 0x0c, 0x61, 0x90,
	0xc1, 0x44, 0xf0, 0xc1, 0x97, 0x51, 0xa3, 0x0c, 0x1c, 0x42, 0xc3, 0x9e, 0x87, 0xeb, 0xae, 0x75,
	0xb0, 0x35, 0xb5, 0x49, 0x05, 0xdf, 0xfc, 0x37, 0xfe, 0x4d, 0x69, 0x93, 0xda, 0x6e, 0x75, 0xc3,
	0xc7, 0xde, 0x9e, 0xef, 0xde, 0x9c, 0x73, 0xa0, 0xe1, 0x89, 0x20, 0x40, 0x4f, 0xcd, 0x44, 0x40,
	0xc3, 0x48, 0x28, 0x41, 0xea, 0xf9, 0x64, 0xec, 0x47, 0xa1, 0xd7, 0x3a, 0xf5, 0x85, 0xf0, 0xe7,
	0xd8, 0x4d, 0x7f, 0x4f, 0xe2, 0xd7, 0x2e, 0x2e, 0x42, 0xf5, 0xa9, 0xd5, 0x76, 0x17, 0x8e, 0x5d,
	0x7c, 0x8f, 0x51, 0xaa, 0x91, 0xc4, 0x68, 0x30, 0x75, 0x51, 0x86, 0x22, 0x90, 0x48, 0x9a, 0x50,
	0x8d, 0xd3, 0xc9, 0x89, 0x75, 0x61, 0x5d, 0xed, 0xba, 0xe6, 0xcb, 0xee, 0xc0, 0xa1, 0xf3, 0x7b,
	0xc0, 0xa0, 0x6b, 0xc5, 0x77, 0x40, 0x8a, 0x62, 0xb3, 0xba, 0x0d, 0xb5, 0xfc, 0x8d, 0x8e, 0x98,
	0xa2, 0xa1, 0x56, 0xa6, 0xf6, 0x0d, 0xec, 0xf5, 0x63, 0xf5, 0x96, 0x1d, 0xf9, 0x2f, 0xf6, 0x6d,
	0xc1, 0xbe, 0xe6, 0xcc, 0x3d, 0x06, 0x3b, 0x0b, 0x94, 0xf2, 0xc5, 0xd7, 0x44, 0xad, 0xd7, 0xa1,
	0x2b, 0x19, 0xd1, 0xa2, 0x9e, 0xba, 0x28, 0xe3, 0xb9, 0x1a, 0x6a, 0xc4, 0xcd, 0xd8, 0x82, 0xc9,
	0xca, 0x92, 0xc9, 0x5b, 0x38, 0x58, 0x22, 0x08, 0x81, 0xda, 0x90, 0x71, 0xde, 0x7f, 0x64, 0xe3,
	0x87, 0xfe, 0xe0, 0x89, 0xdd, 0x37, 0xb6, 0xc8, 0x11, 0xd4, 0xb3, 0x19, 0x1f, 0x39, 0x0e, 0xe3,
	0xbc, 0x61, 0xf5, 0xbe, 0x2a, 0xc5, 0x30, 0x39, 0x46, 0x1f, 0x33, 0x0f, 0xc9, 0x73, 0xb2, 0xaf,
	0x50, 0x09, 0x69, 0x52, 0xdd, 0x20, 0xcd, 0x1a, 0xa4, 0x2c, 0x69, 0xb0, 0xd5, 0x2e, 0xd9, 0xf8,
	0xbb, 0xca, 0x11, 0x40, 0x7e, 0x85, 0xd8, 0x25, 0xaa, 0xd4, 0x67, 0xeb, 0x72, 0xa3, 0xc6, 0xac,
	0x75, 0x60, 0x3b, 0x89, 0x8d, 0x9c, 0xad, 0x49, 0x53, 0xaf, 0x3a, 0xdf, 0x98, 0xf5, 0xa4, 0x9a,
	0x7a, 0xba, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0xee, 0xdf, 0xec, 0xd4, 0xc8, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConnectionServiceClient is the client API for ConnectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConnectionServiceClient interface {
	RequestUserId(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RequestUserIdResponse, error)
	Connection(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionResponse, error)
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type connectionServiceClient struct {
	cc *grpc.ClientConn
}

func NewConnectionServiceClient(cc *grpc.ClientConn) ConnectionServiceClient {
	return &connectionServiceClient{cc}
}

func (c *connectionServiceClient) RequestUserId(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RequestUserIdResponse, error) {
	out := new(RequestUserIdResponse)
	err := c.cc.Invoke(ctx, "/connection_grpc.ConnectionService/RequestUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) Connection(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionResponse, error) {
	out := new(ConnectionResponse)
	err := c.cc.Invoke(ctx, "/connection_grpc.ConnectionService/Connection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/connection_grpc.ConnectionService/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectionServiceServer is the server API for ConnectionService service.
type ConnectionServiceServer interface {
	RequestUserId(context.Context, *empty.Empty) (*RequestUserIdResponse, error)
	Connection(context.Context, *ConnectionRequest) (*ConnectionResponse, error)
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
}

func RegisterConnectionServiceServer(s *grpc.Server, srv ConnectionServiceServer) {
	s.RegisterService(&_ConnectionService_serviceDesc, srv)
}

func _ConnectionService_RequestUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).RequestUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connection_grpc.ConnectionService/RequestUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).RequestUserId(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_Connection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).Connection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connection_grpc.ConnectionService/Connection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).Connection(ctx, req.(*ConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connection_grpc.ConnectionService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConnectionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "connection_grpc.ConnectionService",
	HandlerType: (*ConnectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestUserId",
			Handler:    _ConnectionService_RequestUserId_Handler,
		},
		{
			MethodName: "Connection",
			Handler:    _ConnectionService_Connection_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _ConnectionService_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connection.proto",
}
